In [1]:
%pip install nba_api

Requirement already satisfied: nba_api in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.11.4)
Requirement already satisfied: numpy>=2.1.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nba_api) (2.5.2)
Requirement already satisfied: pandas>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nba_api) (3.0.5)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nba_api) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

from nba_api.stats.endpoints import leaguedashteamstats

print("Imports successful.")

Imports successful.

In [3]:
team_stats_2025 = leaguedashteamstats.LeagueDashTeamStats(
    season="2024-25",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
)

team_stats_2025_df = team_stats_2025.get_data_frames()[0]

team_stats_2025_df.head()

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,82,40,42,0.488,48.2,43.4,91.8,0.472,...,14,2,26,2,12,15,22,8,5,18
1,1610612738,Boston Celtics,82,61,21,0.744,48.4,41.6,90.0,0.462,...,8,16,2,29,5,1,2,27,8,3
2,1610612751,Brooklyn Nets,82,26,56,0.317,48.2,37.6,86.1,0.437,...,29,24,23,20,26,27,28,14,29,26
3,1610612766,Charlotte Hornets,82,19,63,0.232,48.2,38.3,89.1,0.430,...,9,26,25,26,21,23,16,22,30,27
4,1610612741,Chicago Bulls,82,39,43,0.476,48.2,43.2,92.0,0.470,...,3,5,20,24,18,18,6,30,6,20

In [4]:
print(team_stats_2025_df.columns.tolist())

['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK']

In [5]:
team_advanced_2025 = leaguedashteamstats.LeagueDashTeamStats(
    season="2024-25",
    season_type_all_star="Regular Season",
    measure_type_detailed_defense="Advanced",
    per_mode_detailed="PerGame"
)

team_advanced_2025_df = team_advanced_2025.get_data_frames()[0]

print(team_advanced_2025_df.columns.tolist())

['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'OFF_RATING_RANK', 'DEF_RATING_RANK', 'NET_RATING_RANK', 'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'EFG_PCT_RANK', 'TS_PCT_RANK', 'PACE_RANK', 'PIE_RANK']

In [6]:
test_old = leaguedashteamstats.LeagueDashTeamStats(
    season="1996-97",
    season_type_all_star="Regular Season",
    measure_type_detailed_defense="Advanced",
    per_mode_detailed="PerGame"
)

test_old_df = test_old.get_data_frames()[0]

print("Rows:", len(test_old_df))
test_old_df[[
    "TEAM_NAME",
    "W_PCT",
    "OFF_RATING",
    "DEF_RATING",
    "NET_RATING",
    "PACE"
]].head()

Rows: 29

             TEAM_NAME  W_PCT  OFF_RATING  DEF_RATING  NET_RATING   PACE
0        Atlanta Hawks  0.683       106.4       100.3         6.2  88.54
1       Boston Celtics  0.183       102.9       110.1        -7.2  96.78
2    Charlotte Hornets  0.659       109.1       107.1         2.1  90.04
3        Chicago Bulls  0.841       112.4       100.7        11.8  91.50
4  Cleveland Cavaliers  0.512       102.7       100.8         1.9  84.31

In [7]:
test_1986 = leaguedashteamstats.LeagueDashTeamStats(
    season="1985-86",
    season_type_all_star="Regular Season",
    measure_type_detailed_defense="Advanced",
    per_mode_detailed="PerGame"
)

test_1986_df = test_1986.get_data_frames()[0]

print("Rows:", len(test_1986_df))

if len(test_1986_df) > 0:
    display(test_1986_df[[
        "TEAM_NAME",
        "W_PCT",
        "OFF_RATING",
        "DEF_RATING",
        "NET_RATING",
        "PACE"
    ]].head())

Rows: 0

In [8]:
test_1996 = leaguedashteamstats.LeagueDashTeamStats(
    season="1995-96",
    season_type_all_star="Regular Season",
    measure_type_detailed_defense="Advanced",
    per_mode_detailed="PerGame"
)

test_1996_df = test_1996.get_data_frames()[0]

print("Rows:", len(test_1996_df))

Rows: 0

In [9]:
url = "https://www.basketball-reference.com/leagues/NBA_1986.html"

tables = pd.read_html(url)

print("Number of tables found:", len(tables))

ImportError: `Import lxml` failed.  Use pip or conda to install the lxml package.

In [10]:
%pip install lxml

Collecting lxml
  Downloading lxml-6.1.3-cp314-cp314-macosx_10_15_universal2.whl.metadata (3.3 kB)
Downloading lxml-6.1.3-cp314-cp314-macosx_10_15_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 17.3 MB/s  0:00:00 eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.1.3
Note: you may need to restart the kernel to use updated packages.

In [11]:
url = "https://www.basketball-reference.com/leagues/NBA_1986.html"

tables = pd.read_html(url)

print("Number of tables found:", len(tables))

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1082)>

In [1]:
import pandas as pd
import numpy as np

from nba_api.stats.endpoints import leaguedashteamstats

print("Imports successful.")

Imports successful.

In [2]:
url = "https://www.basketball-reference.com/leagues/NBA_1986.html"

tables = pd.read_html(url)

print("Number of tables found:", len(tables))

Number of tables found: 9

In [3]:
for i, table in enumerate(tables):
    print(f"Table {i}:")
    print(table.columns.tolist())
    print()

Table 0:
['Eastern Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']

Table 1:
['Western Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']

Table 2:
['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

Table 3:
['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

Table 4:
['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

Table 5:
['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

Table 6:
['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

Table 7:
['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

Table 8:
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'W'), ('Unnamed: 4_level_0', 'L'), ('Unnamed: 5_level_0', 'PW'), ('Unnamed: 6_level_0', 'PL'), ('Unnamed: 7_level_0', 'MOV'), ('Unnamed: 8_level_0', 'SOS'), ('Unnamed: 9_level_0', 'SRS'), ('Unnamed: 10_level_0', 'ORtg'), ('Unnamed: 11_level_0', 'DRtg'), ('Unnamed: 12_level_0', 'NRtg'), ('Unnamed: 13_level_0', 'Pace'), ('Unnamed: 14_level_0', 'FTr'), ('Unnamed: 15_level_0', '3PAr'), ('Unnamed: 16_level_0', 'TS%'), ('Unnamed: 17_level_0', 'Unnamed: 17_level_1'), ('Offense Four Factors', 'eFG%'), ('Offense Four Factors', 'TOV%'), ('Offense Four Factors', 'ORB%'), ('Offense Four Factors', 'FT/FGA'), ('Unnamed: 22_level_0', 'Unnamed: 22_level_1'), ('Defense Four Factors', 'eFG%'), ('Defense Four Factors', 'TOV%'), ('Defense Four Factors', 'DRB%'), ('Defense Four Factors', 'FT/FGA'), ('Unnamed: 27_level_0', 'Unnamed: 27_level_1'), ('Unnamed: 28_level_0', 'Arena'), ('Unnamed: 29_level_0', 'Attend.'), ('Unnamed: 30_level_0', 'Attend./G')]

In [4]:
advanced_1986 = tables[8].copy()

# Flatten the two-level column names
advanced_1986.columns = [
    col[1] if col[1] and not str(col[1]).startswith("Unnamed") else col[0]
    for col in advanced_1986.columns
]

print(advanced_1986.columns.tolist())

['Rk', 'Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'Unnamed: 17_level_0', 'eFG%', 'TOV%', 'ORB%', 'FT/FGA', 'Unnamed: 22_level_0', 'eFG%', 'TOV%', 'DRB%', 'FT/FGA', 'Unnamed: 27_level_0', 'Arena', 'Attend.', 'Attend./G']

In [5]:
advanced_1986 = tables[8].copy()

new_columns = []

for top, bottom in advanced_1986.columns:
    if top == "Offense Four Factors":
        new_columns.append("OFF_" + bottom)
    elif top == "Defense Four Factors":
        new_columns.append("DEF_" + bottom)
    elif bottom and not str(bottom).startswith("Unnamed"):
        new_columns.append(bottom)
    else:
        new_columns.append(top)

advanced_1986.columns = new_columns

print(advanced_1986.columns.tolist())

['Rk', 'Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'Unnamed: 17_level_0', 'OFF_eFG%', 'OFF_TOV%', 'OFF_ORB%', 'OFF_FT/FGA', 'Unnamed: 22_level_0', 'DEF_eFG%', 'DEF_TOV%', 'DEF_DRB%', 'DEF_FT/FGA', 'Unnamed: 27_level_0', 'Arena', 'Attend.', 'Attend./G']

In [6]:
advanced_1986 = advanced_1986.loc[
    :, ~advanced_1986.columns.str.startswith("Unnamed")
]

advanced_1986.head(10)

,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,OFF_TOV%,OFF_ORB%,OFF_FT/FGA,DEF_eFG%,DEF_TOV%,DEF_DRB%,DEF_FT/FGA,Arena,Attend.,Attend./G
0,1.0,Boston Celtics*,29.3,67.0,15.0,63,19,9.41,-0.36,9.06,...,14.1,31.3,0.244,0.466,13.0,71.7,0.216,Boston Garden,610571,14890
1,2.0,Milwaukee Bucks*,26.0,57.0,25.0,62,20,9.04,-0.35,8.69,...,13.9,33.8,0.282,0.473,16.6,67.4,0.281,MECCA Arena,443064,10806
2,3.0,Los Angeles Lakers*,28.1,62.0,20.0,59,23,7.74,-0.91,6.84,...,14.9,33.1,0.247,0.484,13.5,69.8,0.239,The Forum,691071,16855
3,4.0,Houston Rockets*,26.0,51.0,31.0,48,34,2.61,-0.51,2.10,...,13.6,35.5,0.232,0.497,14.8,67.2,0.243,The Summit,604644,14747
4,5.0,Atlanta Hawks*,25.3,50.0,32.0,47,35,2.37,0.22,2.59,...,15.3,34.9,0.282,0.481,15.4,66.7,0.269,Omni Coliseum,377351,9204
5,6.0,Philadelphia 76ers*,28.0,54.0,28.0,47,35,2.35,0.11,2.46,...,16.1,37.3,0.302,0.499,15.6,66.7,0.211,The Spectrum,513459,12506
6,7.0,Denver Nuggets*,28.1,47.0,35.0,44,38,1.30,-0.42,0.89,...,13.0,30.9,0.245,0.495,16.9,64.1,0.266,McNichols Sports Arena,531824,12971
7,8.0,Dallas Mavericks*,25.8,44.0,38.0,44,38,1.10,-0.40,0.70,...,13.3,30.0,0.283,0.508,13.0,66.8,0.201,Reunion Arena,693052,16904
8,9.0,Detroit Pistons*,26.5,46.0,36.0,44,38,1.17,0.27,1.44,...,13.3,33.5,0.232,0.496,14.9,67.6,0.266,Pontiac Silverdome,695233,16957
9,10.0,Portland Trail Blazers*,26.6,40.0,42.0,44,38,1.06,-0.45,0.61,...,15.2,32.8,0.294,0.507,16.4,66.3,0.275,Memorial Coliseum,519306,12666

In [15]:
import time

def get_team_season_data(end_year):
    """
    Collect Basketball Reference advanced team data for one NBA season.

    Example:
    end_year=1986 retrieves the 1985-86 season.
    """

    url = f"https://www.basketball-reference.com/leagues/NBA_{end_year}.html"
    tables = pd.read_html(url)

    # Find the advanced team statistics table automatically
    df = None

    for table in tables:
        if table.columns.nlevels == 2:
            bottom_level = [str(col[1]) for col in table.columns]

            if (
                "Team" in bottom_level
                and "ORtg" in bottom_level
                and "DRtg" in bottom_level
                and "SRS" in bottom_level
            ):
                df = table.copy()
                break

    if df is None:
        raise ValueError(
            f"Advanced team statistics table not found for {end_year}"
        )

    # Preserve offense/defense labels when flattening headers
    new_columns = []

    for top, bottom in df.columns:
        if top == "Offense Four Factors":
            new_columns.append("OFF_" + bottom)
        elif top == "Defense Four Factors":
            new_columns.append("DEF_" + bottom)
        elif bottom and not str(bottom).startswith("Unnamed"):
            new_columns.append(bottom)
        else:
            new_columns.append(top)

    df.columns = new_columns

    # Remove separator columns
    df = df.loc[:, ~df.columns.str.startswith("Unnamed")]

    # Remove playoff asterisk from team names
    df["Team"] = (
        df["Team"]
        .str.replace("*", "", regex=False)
        .str.strip()
    )

    # Remove League Average row
    df = df[df["Team"] != "League Average"].copy()

    # Add season identifiers
    df["Season_End"] = end_year
    df["Season"] = f"{end_year - 1}-{str(end_year)[-2:]}"

    return df

In [8]:
test_season = get_team_season_data(1986)

print(test_season.shape)

test_season[
    ["Season", "Team", "W", "L", "MOV", "SOS", "SRS",
     "ORtg", "DRtg", "NRtg", "Pace"]
].head(10)

(24, 30)

,Season,Team,W,L,MOV,SOS,SRS,ORtg,DRtg,NRtg,Pace
0,1985-86,Boston Celtics,67.0,15.0,9.41,-0.36,9.06,111.8,102.6,9.2,101.2
1,1985-86,Milwaukee Bucks,57.0,25.0,9.04,-0.35,8.69,111.4,102.7,8.7,102.1
2,1985-86,Los Angeles Lakers,62.0,20.0,7.74,-0.91,6.84,113.3,105.8,7.5,102.7
3,1985-86,Houston Rockets,51.0,31.0,2.61,-0.51,2.10,110.1,107.6,2.5,103.5
4,1985-86,Atlanta Hawks,50.0,32.0,2.37,0.22,2.59,107.9,105.6,2.3,100.0
5,1985-86,Philadelphia 76ers,54.0,28.0,2.35,0.11,2.46,108.6,106.3,2.3,100.5
6,1985-86,Denver Nuggets,47.0,35.0,1.30,-0.42,0.89,107.1,105.9,1.2,106.7
7,1985-86,Dallas Mavericks,44.0,38.0,1.10,-0.40,0.70,112.1,111.0,1.1,102.2
8,1985-86,Detroit Pistons,46.0,36.0,1.17,0.27,1.44,109.0,107.9,1.1,104.2
9,1985-86,Portland Trail Blazers,40.0,42.0,1.06,-0.45,0.61,109.2,108.2,1.0,104.5

In [9]:
test_season[["Team", "W", "L"]].tail(5)

                     Team     W     L
19  Golden State Warriors  30.0  52.0
20          Chicago Bulls  30.0  52.0
21        New York Knicks  23.0  59.0
22   Los Angeles Clippers  32.0  50.0
23         League Average   NaN   NaN

In [11]:
test_season = get_team_season_data(1986)

print(test_season.shape)
print(test_season["Team"].tail())

(23, 30)
18           Indiana Pacers
19    Golden State Warriors
20            Chicago Bulls
21          New York Knicks
22     Los Angeles Clippers
Name: Team, dtype: str

In [12]:
print(test_season.columns.tolist())

['Rk', 'Team', 'Age', 'W', 'L', 'PW', 'PL', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'OFF_eFG%', 'OFF_TOV%', 'OFF_ORB%', 'OFF_FT/FGA', 'DEF_eFG%', 'DEF_TOV%', 'DEF_DRB%', 'DEF_FT/FGA', 'Arena', 'Attend.', 'Attend./G', 'Season_End', 'Season']

In [13]:
all_seasons = []
failed_seasons = []

# 1986 = 1985-86 season
# 2026 = 2025-26 season
for end_year in range(1986, 2027):

    season_name = f"{end_year - 1}-{str(end_year)[-2:]}"
    print(f"Collecting {season_name}...")

    try:
        season_df = get_team_season_data(end_year)

        all_seasons.append(season_df)

        # Save an individual backup for this season
        season_df.to_csv(
            f"../data/team_stats_{season_name}.csv",
            index=False
        )

        print(f"✓ {season_name}: {len(season_df)} teams")

    except Exception as e:
        failed_seasons.append((season_name, str(e)))
        print(f"✗ {season_name} FAILED: {e}")

    # Be respectful of Basketball Reference's request limits
    time.sleep(4)

print("\nCollection finished.")
print("Successful seasons:", len(all_seasons))
print("Failed seasons:", len(failed_seasons))

Collecting 1985-86...
✓ 1985-86: 23 teams
Collecting 1986-87...
✓ 1986-87: 23 teams
Collecting 1987-88...
✓ 1987-88: 23 teams
Collecting 1988-89...
✓ 1988-89: 25 teams
Collecting 1989-90...
✓ 1989-90: 27 teams
Collecting 1990-91...
✓ 1990-91: 27 teams
Collecting 1991-92...
✓ 1991-92: 27 teams
Collecting 1992-93...
✓ 1992-93: 27 teams
Collecting 1993-94...
✓ 1993-94: 27 teams
Collecting 1994-95...
✓ 1994-95: 27 teams
Collecting 1995-96...
✓ 1995-96: 29 teams
Collecting 1996-97...
✓ 1996-97: 29 teams
Collecting 1997-98...
✓ 1997-98: 29 teams
Collecting 1998-99...
✓ 1998-99: 29 teams
Collecting 1999-00...
✓ 1999-00: 29 teams
Collecting 2000-01...
✓ 2000-01: 29 teams
Collecting 2001-02...
✓ 2001-02: 29 teams
Collecting 2002-03...
✓ 2002-03: 29 teams
Collecting 2003-04...
✓ 2003-04: 29 teams
Collecting 2004-05...
✓ 2004-05: 30 teams
Collecting 2005-06...
✓ 2005-06: 30 teams
Collecting 2006-07...
✓ 2006-07: 30 teams
Collecting 2007-08...
✓ 2007-08: 30 teams
Collecting 2008-09...
✓ 2008-09: 30 teams
Collecting 2009-10...
✓ 2009-10: 30 teams
Collecting 2010-11...
✓ 2010-11: 30 teams
Collecting 2011-12...
✓ 2011-12: 30 teams
Collecting 2012-13...
✓ 2012-13: 30 teams
Collecting 2013-14...
✓ 2013-14: 30 teams
Collecting 2014-15...
✓ 2014-15: 30 teams
Collecting 2015-16...
✗ 2015-16 FAILED: too many values to unpack (expected 2)
Collecting 2016-17...
✗ 2016-17 FAILED: too many values to unpack (expected 2)
Collecting 2017-18...
✗ 2017-18 FAILED: too many values to unpack (expected 2)
Collecting 2018-19...
✗ 2018-19 FAILED: too many values to unpack (expected 2)
Collecting 2019-20...
✗ 2019-20 FAILED: too many values to unpack (expected 2)
Collecting 2020-21...
✗ 2020-21 FAILED: too many values to unpack (expected 2)
Collecting 2021-22...
✗ 2021-22 FAILED: too many values to unpack (expected 2)
Collecting 2022-23...
✗ 2022-23 FAILED: too many values to unpack (expected 2)
Collecting 2023-24...
✗ 2023-24 FAILED: too many values to unpack (expected 2)
Collecting 2024-25...
✗ 2024-25 FAILED: too many values to unpack (expected 2)
Collecting 2025-26...
✗ 2025-26 FAILED: too many values to unpack (expected 2)

Collection finished.
Successful seasons: 30
Failed seasons: 11

In [14]:
url_2016 = "https://www.basketball-reference.com/leagues/NBA_2016.html"

tables_2016 = pd.read_html(url_2016)

print("Number of tables:", len(tables_2016))

for i, table in enumerate(tables_2016):
    print(f"\nTable {i}:")
    print("Column levels:", table.columns.nlevels)
    print(table.columns.tolist()[:5])

Number of tables: 13

Table 0:
Column levels: 1
['Eastern Conference', 'W', 'L', 'W/L%', 'GB']

Table 1:
Column levels: 1
['Western Conference', 'W', 'L', 'W/L%', 'GB']

Table 2:
Column levels: 1
['Eastern Conference', 'W', 'L', 'W/L%', 'GB']

Table 3:
Column levels: 1
['Western Conference', 'W', 'L', 'W/L%', 'GB']

Table 4:
Column levels: 1
['Rk', 'Team', 'G', 'MP', 'FG']

Table 5:
Column levels: 1
['Rk', 'Team', 'G', 'MP', 'FG']

Table 6:
Column levels: 1
['Rk', 'Team', 'G', 'MP', 'FG']

Table 7:
Column levels: 1
['Rk', 'Team', 'G', 'MP', 'FG']

Table 8:
Column levels: 1
['Rk', 'Team', 'G', 'MP', 'FG']

Table 9:
Column levels: 1
['Rk', 'Team', 'G', 'MP', 'FG']

Table 10:
Column levels: 2
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'W'), ('Unnamed: 4_level_0', 'L')]

Table 11:
Column levels: 2
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'G'), ('Unnamed: 3_level_0', 'MP'), ('Unnamed: 4_level_0', 'FG%')]

Table 12:
Column levels: 2
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Team'), ('Unnamed: 2_level_0', 'G'), ('Unnamed: 3_level_0', 'MP'), ('Unnamed: 4_level_0', 'FG%')]

In [16]:
test_2016 = get_team_season_data(2016)

print(test_2016.shape)

test_2016[
    ["Season", "Team", "W", "L", "MOV", "SOS", "SRS",
     "ORtg", "DRtg", "NRtg", "Pace"]
].head()

(30, 30)

,Season,Team,W,L,MOV,SOS,SRS,ORtg,DRtg,NRtg,Pace
0,2015-16,San Antonio Spurs,67.0,15.0,10.63,-0.36,10.28,110.3,99.0,11.3,93.8
1,2015-16,Golden State Warriors,73.0,9.0,10.76,-0.38,10.38,114.5,103.8,10.7,99.3
2,2015-16,Oklahoma City Thunder,55.0,27.0,7.28,-0.19,7.09,113.1,105.6,7.5,96.7
3,2015-16,Cleveland Cavaliers,57.0,25.0,6.00,-0.55,5.45,110.9,104.5,6.4,93.3
4,2015-16,Toronto Raptors,56.0,26.0,4.50,-0.42,4.08,110.0,105.2,4.8,92.9

In [17]:
missing_seasons = []
failed_missing_seasons = []

# Collect only 2015-16 through 2025-26
for end_year in range(2016, 2027):

    season_name = f"{end_year - 1}-{str(end_year)[-2:]}"
    print(f"Collecting {season_name}...")

    try:
        season_df = get_team_season_data(end_year)

        missing_seasons.append(season_df)

        # Save individual season backup
        season_df.to_csv(
            f"../data/team_stats_{season_name}.csv",
            index=False
        )

        print(f"✓ {season_name}: {len(season_df)} teams")

    except Exception as e:
        failed_missing_seasons.append((season_name, str(e)))
        print(f"✗ {season_name} FAILED: {e}")

    time.sleep(4)

print("\nCollection finished.")
print("Successful missing seasons:", len(missing_seasons))
print("Failed missing seasons:", len(failed_missing_seasons))

Collecting 2015-16...
✓ 2015-16: 30 teams
Collecting 2016-17...
✓ 2016-17: 30 teams
Collecting 2017-18...
✓ 2017-18: 30 teams
Collecting 2018-19...
✓ 2018-19: 30 teams
Collecting 2019-20...
✓ 2019-20: 30 teams
Collecting 2020-21...
✓ 2020-21: 30 teams
Collecting 2021-22...
✓ 2021-22: 30 teams
Collecting 2022-23...
✓ 2022-23: 30 teams
Collecting 2023-24...
✓ 2023-24: 30 teams
Collecting 2024-25...
✓ 2024-25: 30 teams
Collecting 2025-26...
✓ 2025-26: 30 teams

Collection finished.
Successful missing seasons: 11
Failed missing seasons: 0

In [18]:
# Combine the original 30 seasons with the 11 missing seasons
all_team_seasons = pd.concat(
    all_seasons + missing_seasons,
    ignore_index=True
)

# Sort chronologically
all_team_seasons = all_team_seasons.sort_values(
    ["Season_End", "Team"]
).reset_index(drop=True)

print("Total rows:", len(all_team_seasons))
print("Total seasons:", all_team_seasons["Season"].nunique())
print("First season:", all_team_seasons["Season"].iloc[0])
print("Last season:", all_team_seasons["Season"].iloc[-1])

all_team_seasons.head()

Total rows: 1177
Total seasons: 41
First season: 1985-86
Last season: 2025-26

,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,OFF_FT/FGA,DEF_eFG%,DEF_TOV%,DEF_DRB%,DEF_FT/FGA,Arena,Attend.,Attend./G,Season_End,Season
0,5.0,Atlanta Hawks,25.3,50.0,32.0,47,35,2.37,0.22,2.59,...,0.282,0.481,15.4,66.7,0.269,Omni Coliseum,377351.0,9204.0,1986,1985-86
1,1.0,Boston Celtics,29.3,67.0,15.0,63,19,9.41,-0.36,9.06,...,0.244,0.466,13.0,71.7,0.216,Boston Garden,610571.0,14890.0,1986,1985-86
2,21.0,Chicago Bulls,26.6,30.0,52.0,31,51,-3.80,0.69,-3.12,...,0.266,0.509,13.5,67.4,0.280,Chicago Stadium,469226.0,11445.0,1986,1985-86
3,16.0,Cleveland Cavaliers,27.0,29.0,53.0,34,48,-2.87,0.68,-2.19,...,0.241,0.480,13.6,68.5,0.292,Coliseum at Richfield,391842.0,9557.0,1986,1985-86
4,8.0,Dallas Mavericks,25.8,44.0,38.0,44,38,1.10,-0.40,0.70,...,0.283,0.508,13.0,66.8,0.201,Reunion Arena,693052.0,16904.0,1986,1985-86

In [19]:
# -----------------------------
# DATA QUALITY CHECKS
# -----------------------------

print("=== BASIC CHECKS ===")
print("Rows:", len(all_team_seasons))
print("Seasons:", all_team_seasons["Season"].nunique())

# Check duplicate team-seasons
duplicates = all_team_seasons.duplicated(
    subset=["Season", "Team"]
).sum()

print("Duplicate team-seasons:", duplicates)

# Check team counts by season
print("\n=== TEAM COUNTS BY SEASON ===")
team_counts = (
    all_team_seasons
    .groupby("Season")
    .size()
)

print(team_counts.to_string())

# Check missing values in important modeling variables
important_columns = [
    "W", "L", "MOV", "SOS", "SRS",
    "ORtg", "DRtg", "NRtg", "Pace"
]

print("\n=== MISSING VALUES ===")
print(all_team_seasons[important_columns].isna().sum())

# Check whether W + L matches expected season length
all_team_seasons["Games"] = (
    all_team_seasons["W"] +
    all_team_seasons["L"]
)

print("\n=== GAMES PLAYED DISTRIBUTION ===")
print(
    all_team_seasons["Games"]
    .value_counts()
    .sort_index()
    .to_string()
)

# Check numeric ranges for major variables
print("\n=== VARIABLE RANGES ===")

for col in ["SRS", "ORtg", "DRtg", "NRtg", "Pace"]:
    print(
        f"{col}: "
        f"{all_team_seasons[col].min()} to "
        f"{all_team_seasons[col].max()}"
    )

=== BASIC CHECKS ===
Rows: 1177
Seasons: 41
Duplicate team-seasons: 0

=== TEAM COUNTS BY SEASON ===
Season
1985-86    23
1986-87    23
1987-88    23
1988-89    25
1989-90    27
1990-91    27
1991-92    27
1992-93    27
1993-94    27
1994-95    27
1995-96    29
1996-97    29
1997-98    29
1998-99    29
1999-00    29
2000-01    29
2001-02    29
2002-03    29
2003-04    29
2004-05    30
2005-06    30
2006-07    30
2007-08    30
2008-09    30
2009-10    30
2010-11    30
2011-12    30
2012-13    30
2013-14    30
2014-15    30
2015-16    30
2016-17    30
2017-18    30
2018-19    30
2019-20    30
2020-21    30
2021-22    30
2022-23    30
2023-24    30
2024-25    30
2025-26    30

=== MISSING VALUES ===
W       0
L       0
MOV     0
SOS     0
SRS     0
ORtg    0
DRtg    0
NRtg    0
Pace    0
dtype: int64

=== GAMES PLAYED DISTRIBUTION ===
Games
50.0      29
64.0       1
65.0       4
66.0      32
67.0       1
71.0       2
72.0      40
73.0       8
74.0       1
75.0       1
81.0       2
82.0    1056

=== VARIABLE RANGES ===
SRS: -14.68 to 12.7
ORtg: 92.2 to 123.2
DRtg: 94.1 to 122.7
NRtg: -15.2 to 13.4
Pace: 82.3 to 113.7

In [20]:
# Save official master team-season dataset
all_team_seasons.to_csv(
    "../data/nba_team_seasons_1986_2026.csv",
    index=False
)

print("Master team-season dataset saved.")
print("Rows:", len(all_team_seasons))
print("Columns:", len(all_team_seasons.columns))

Master team-season dataset saved.
Rows: 1177
Columns: 31

In [21]:
playoff_url_2016 = "https://www.basketball-reference.com/playoffs/NBA_2016_games.html"

playoff_tables_2016 = pd.read_html(playoff_url_2016)

print("Number of tables found:", len(playoff_tables_2016))

for i, table in enumerate(playoff_tables_2016):
    print(f"\nTable {i}:")
    print("Shape:", table.shape)
    print("Columns:", table.columns.tolist())

Number of tables found: 1

Table 0:
Shape: (86, 12)
Columns: ['Date', 'Start (ET)', 'Visitor/Neutral', 'PTS', 'Home/Neutral', 'PTS.1', 'Unnamed: 6', 'Unnamed: 7', 'Attend.', 'LOG', 'Arena', 'Notes']

In [22]:
playoffs_2016 = playoff_tables_2016[0].copy()

# Keep only the columns we need
playoffs_2016 = playoffs_2016[
    ["Date", "Visitor/Neutral", "PTS", "Home/Neutral", "PTS.1"]
].copy()

# Rename columns
playoffs_2016.columns = [
    "Date",
    "Away_Team",
    "Away_PTS",
    "Home_Team",
    "Home_PTS"
]

# Add season
playoffs_2016["Season"] = "2015-16"
playoffs_2016["Season_End"] = 2016

# Convert scores to numeric
playoffs_2016["Away_PTS"] = pd.to_numeric(
    playoffs_2016["Away_PTS"],
    errors="coerce"
)

playoffs_2016["Home_PTS"] = pd.to_numeric(
    playoffs_2016["Home_PTS"],
    errors="coerce"
)

# Create target variable:
# 1 = home team won, 0 = away team won
playoffs_2016["Home_Win"] = (
    playoffs_2016["Home_PTS"] > playoffs_2016["Away_PTS"]
).astype(int)

# Put columns in a convenient order
playoffs_2016 = playoffs_2016[
    [
        "Season",
        "Season_End",
        "Date",
        "Away_Team",
        "Away_PTS",
        "Home_Team",
        "Home_PTS",
        "Home_Win"
    ]
]

print(playoffs_2016.shape)
playoffs_2016.head()

(86, 8)

,Season,Season_End,Date,Away_Team,Away_PTS,Home_Team,Home_PTS,Home_Win
0,2015-16,2016,"Sat, Apr 16, 2016",Indiana Pacers,100,Toronto Raptors,90,0
1,2015-16,2016,"Sat, Apr 16, 2016",Houston Rockets,78,Golden State Warriors,104,1
2,2015-16,2016,"Sat, Apr 16, 2016",Boston Celtics,101,Atlanta Hawks,102,1
3,2015-16,2016,"Sat, Apr 16, 2016",Dallas Mavericks,70,Oklahoma City Thunder,108,1
4,2015-16,2016,"Sun, Apr 17, 2016",Detroit Pistons,101,Cleveland Cavaliers,106,1

In [23]:
playoffs_2016.tail(10)

,Season,Season_End,Date,Away_Team,Away_PTS,Home_Team,Home_PTS,Home_Win
76,2015-16,2016,"Fri, May 27, 2016",Cleveland Cavaliers,113,Toronto Raptors,87,0
77,2015-16,2016,"Sat, May 28, 2016",Golden State Warriors,108,Oklahoma City Thunder,101,0
78,2015-16,2016,"Mon, May 30, 2016",Oklahoma City Thunder,88,Golden State Warriors,96,1
79,2015-16,2016,"Thu, Jun 2, 2016",Cleveland Cavaliers,89,Golden State Warriors,104,1
80,2015-16,2016,"Sun, Jun 5, 2016",Cleveland Cavaliers,77,Golden State Warriors,110,1
81,2015-16,2016,"Wed, Jun 8, 2016",Golden State Warriors,90,Cleveland Cavaliers,120,1
82,2015-16,2016,"Fri, Jun 10, 2016",Golden State Warriors,108,Cleveland Cavaliers,97,0
83,2015-16,2016,"Mon, Jun 13, 2016",Cleveland Cavaliers,112,Golden State Warriors,97,0
84,2015-16,2016,"Thu, Jun 16, 2016",Golden State Warriors,101,Cleveland Cavaliers,115,1
85,2015-16,2016,"Sun, Jun 19, 2016",Cleveland Cavaliers,93,Golden State Warriors,89,0

In [24]:
playoff_url_1986 = "https://www.basketball-reference.com/playoffs/NBA_1986_games.html"

playoff_tables_1986 = pd.read_html(playoff_url_1986)

print("Number of tables found:", len(playoff_tables_1986))

for i, table in enumerate(playoff_tables_1986):
    print(f"\nTable {i}:")
    print("Shape:", table.shape)
    print("Columns:", table.columns.tolist())

Number of tables found: 1

Table 0:
Shape: (68, 12)
Columns: ['Date', 'Start (ET)', 'Visitor/Neutral', 'PTS', 'Home/Neutral', 'PTS.1', 'Unnamed: 6', 'Unnamed: 7', 'Attend.', 'LOG', 'Arena', 'Notes']

In [25]:
def get_playoff_games(end_year):
    """
    Collect every NBA playoff game for one season from Basketball Reference.

    Example:
    end_year=1986 retrieves the 1985-86 playoffs.
    """

    url = f"https://www.basketball-reference.com/playoffs/NBA_{end_year}_games.html"

    tables = pd.read_html(url)
    df = tables[0].copy()

    # Keep only the fields needed for modeling
    df = df[
        ["Date", "Visitor/Neutral", "PTS", "Home/Neutral", "PTS.1"]
    ].copy()

    # Rename columns
    df.columns = [
        "Date",
        "Away_Team",
        "Away_PTS",
        "Home_Team",
        "Home_PTS"
    ]

    # Convert scores to numeric
    df["Away_PTS"] = pd.to_numeric(df["Away_PTS"], errors="coerce")
    df["Home_PTS"] = pd.to_numeric(df["Home_PTS"], errors="coerce")

    # Remove any rows that are not completed games
    df = df.dropna(subset=["Away_PTS", "Home_PTS"]).copy()

    # Convert scores to integers
    df["Away_PTS"] = df["Away_PTS"].astype(int)
    df["Home_PTS"] = df["Home_PTS"].astype(int)

    # Add season identifiers
    df["Season_End"] = end_year
    df["Season"] = f"{end_year - 1}-{str(end_year)[-2:]}"

    # Create modeling target
    # 1 = home team won
    # 0 = away team won
    df["Home_Win"] = (
        df["Home_PTS"] > df["Away_PTS"]
    ).astype(int)

    # Arrange columns
    df = df[
        [
            "Season",
            "Season_End",
            "Date",
            "Away_Team",
            "Away_PTS",
            "Home_Team",
            "Home_PTS",
            "Home_Win"
        ]
    ]

    return df

In [26]:
test_playoffs_1986 = get_playoff_games(1986)
test_playoffs_2016 = get_playoff_games(2016)

print("1985-86:", test_playoffs_1986.shape)
print("2015-16:", test_playoffs_2016.shape)

print("\n1986 final game:")
display(test_playoffs_1986.tail(1))

print("\n2016 final game:")
display(test_playoffs_2016.tail(1))

1985-86: (68, 8)
2015-16: (86, 8)

1986 final game:

,Season,Season_End,Date,Away_Team,Away_PTS,Home_Team,Home_PTS,Home_Win
67,1985-86,1986,"Sun, Jun 8, 1986",Houston Rockets,97,Boston Celtics,114,1

2016 final game:

,Season,Season_End,Date,Away_Team,Away_PTS,Home_Team,Home_PTS,Home_Win
85,2015-16,2016,"Sun, Jun 19, 2016",Cleveland Cavaliers,93,Golden State Warriors,89,0

In [27]:
all_playoff_seasons = []
failed_playoff_seasons = []

# 1985-86 through 2024-25
for end_year in range(1986, 2026):

    season_name = f"{end_year - 1}-{str(end_year)[-2:]}"
    print(f"Collecting {season_name} playoffs...")

    try:
        playoff_df = get_playoff_games(end_year)

        all_playoff_seasons.append(playoff_df)

        # Save individual season backup
        playoff_df.to_csv(
            f"../data/playoff_games_{season_name}.csv",
            index=False
        )

        print(f"✓ {season_name}: {len(playoff_df)} games")

    except Exception as e:
        failed_playoff_seasons.append((season_name, str(e)))
        print(f"✗ {season_name} FAILED: {e}")

    # Respect Basketball Reference request limits
    time.sleep(4)

print("\nCollection finished.")
print("Successful playoff seasons:", len(all_playoff_seasons))
print("Failed playoff seasons:", len(failed_playoff_seasons))

Collecting 1985-86 playoffs...
✓ 1985-86: 68 games
Collecting 1986-87 playoffs...
✓ 1986-87: 71 games
Collecting 1987-88 playoffs...
✓ 1987-88: 80 games
Collecting 1988-89 playoffs...
✓ 1988-89: 62 games
Collecting 1989-90 playoffs...
✓ 1989-90: 72 games
Collecting 1990-91 playoffs...
✓ 1990-91: 68 games
Collecting 1991-92 playoffs...
✓ 1991-92: 73 games
Collecting 1992-93 playoffs...
✓ 1992-93: 76 games
Collecting 1993-94 playoffs...
✓ 1993-94: 77 games
Collecting 1994-95 playoffs...
✓ 1994-95: 73 games
Collecting 1995-96 playoffs...
✓ 1995-96: 68 games
Collecting 1996-97 playoffs...
✓ 1996-97: 72 games
Collecting 1997-98 playoffs...
✓ 1997-98: 71 games
Collecting 1998-99 playoffs...
✓ 1998-99: 66 games
Collecting 1999-00 playoffs...
✓ 1999-00: 75 games
Collecting 2000-01 playoffs...
✓ 2000-01: 71 games
Collecting 2001-02 playoffs...
✓ 2001-02: 71 games
Collecting 2002-03 playoffs...
✓ 2002-03: 88 games
Collecting 2003-04 playoffs...
✓ 2003-04: 82 games
Collecting 2004-05 playoffs...
✓ 2004-05: 84 games
Collecting 2005-06 playoffs...
✓ 2005-06: 89 games
Collecting 2006-07 playoffs...
✓ 2006-07: 79 games
Collecting 2007-08 playoffs...
✓ 2007-08: 86 games
Collecting 2008-09 playoffs...
✓ 2008-09: 85 games
Collecting 2009-10 playoffs...
✓ 2009-10: 82 games
Collecting 2010-11 playoffs...
✓ 2010-11: 81 games
Collecting 2011-12 playoffs...
✓ 2011-12: 84 games
Collecting 2012-13 playoffs...
✓ 2012-13: 85 games
Collecting 2013-14 playoffs...
✓ 2013-14: 89 games
Collecting 2014-15 playoffs...
✓ 2014-15: 81 games
Collecting 2015-16 playoffs...
✓ 2015-16: 86 games
Collecting 2016-17 playoffs...
✓ 2016-17: 79 games
Collecting 2017-18 playoffs...
✓ 2017-18: 82 games
Collecting 2018-19 playoffs...
✓ 2018-19: 82 games
Collecting 2019-20 playoffs...
✓ 2019-20: 83 games
Collecting 2020-21 playoffs...
✓ 2020-21: 85 games
Collecting 2021-22 playoffs...
✓ 2021-22: 87 games
Collecting 2022-23 playoffs...
✓ 2022-23: 84 games
Collecting 2023-24 playoffs...
✓ 2023-24: 82 games
Collecting 2024-25 playoffs...
✓ 2024-25: 84 games

Collection finished.
Successful playoff seasons: 40
Failed playoff seasons: 0

In [28]:
# Combine all playoff seasons
all_playoff_games = pd.concat(
    all_playoff_seasons,
    ignore_index=True
)

# Convert Date to datetime
all_playoff_games["Date"] = pd.to_datetime(
    all_playoff_games["Date"]
)

# Sort chronologically
all_playoff_games = all_playoff_games.sort_values(
    ["Season_End", "Date"]
).reset_index(drop=True)

print("=== BASIC CHECKS ===")
print("Total playoff games:", len(all_playoff_games))
print("Total seasons:", all_playoff_games["Season"].nunique())
print("First season:", all_playoff_games["Season"].iloc[0])
print("Last season:", all_playoff_games["Season"].iloc[-1])

# Check duplicate games
duplicates = all_playoff_games.duplicated(
    subset=[
        "Season",
        "Date",
        "Away_Team",
        "Home_Team"
    ]
).sum()

print("Duplicate games:", duplicates)

# Check missing values
print("\n=== MISSING VALUES ===")
print(all_playoff_games.isna().sum())

# Home-court win rate
print("\n=== HOME WIN RATE ===")
print(all_playoff_games["Home_Win"].value_counts())
print(
    "Home win percentage:",
    round(all_playoff_games["Home_Win"].mean(), 3)
)

# Games per postseason
print("\n=== GAMES PER POSTSEASON ===")
games_by_season = (
    all_playoff_games
    .groupby("Season")
    .size()
)

print(games_by_season.to_string())

# Final game from first and last completed postseason
print("\n=== FIRST POSTSEASON FINAL GAME ===")
display(
    all_playoff_games[
        all_playoff_games["Season"] == "1985-86"
    ].tail(1)
)

print("\n=== MOST RECENT POSTSEASON FINAL GAME ===")
display(
    all_playoff_games[
        all_playoff_games["Season"] == "2024-25"
    ].tail(1)
)

=== BASIC CHECKS ===
Total playoff games: 3143
Total seasons: 40
First season: 1985-86
Last season: 2024-25
Duplicate games: 0

=== MISSING VALUES ===
Season        0
Season_End    0
Date          0
Away_Team     0
Away_PTS      0
Home_Team     0
Home_PTS      0
Home_Win      0
dtype: int64

=== HOME WIN RATE ===
Home_Win
1    2007
0    1136
Name: count, dtype: int64
Home win percentage: 0.639

=== GAMES PER POSTSEASON ===
Season
1985-86    68
1986-87    71
1987-88    80
1988-89    62
1989-90    72
1990-91    68
1991-92    73
1992-93    76
1993-94    77
1994-95    73
1995-96    68
1996-97    72
1997-98    71
1998-99    66
1999-00    75
2000-01    71
2001-02    71
2002-03    88
2003-04    82
2004-05    84
2005-06    89
2006-07    79
2007-08    86
2008-09    85
2009-10    82
2010-11    81
2011-12    84
2012-13    85
2013-14    89
2014-15    81
2015-16    86
2016-17    79
2017-18    82
2018-19    82
2019-20    83
2020-21    85
2021-22    87
2022-23    84
2023-24    82
2024-25    84

=== FIRST POSTSEASON FINAL GAME ===

,Season,Season_End,Date,Away_Team,Away_PTS,Home_Team,Home_PTS,Home_Win
67,1985-86,1986,1986-06-08,Houston Rockets,97,Boston Celtics,114,1

=== MOST RECENT POSTSEASON FINAL GAME ===

,Season,Season_End,Date,Away_Team,Away_PTS,Home_Team,Home_PTS,Home_Win
3142,2024-25,2025,2025-06-22,Indiana Pacers,91,Oklahoma City Thunder,103,1

In [29]:
all_playoff_games.to_csv(
    "../data/nba_playoff_games_1986_2025.csv",
    index=False
)

print("Master playoff-game dataset saved.")
print("Rows:", len(all_playoff_games))
print("Columns:", len(all_playoff_games.columns))

Master playoff-game dataset saved.
Rows: 3143
Columns: 8

In [30]:
all_team_seasons["W_PCT"] = (
    all_team_seasons["W"] /
    (all_team_seasons["W"] + all_team_seasons["L"])
)

all_team_seasons[
    ["Season", "Team", "W", "L", "W_PCT"]
].head()

    Season                 Team     W     L     W_PCT
0  1985-86        Atlanta Hawks  50.0  32.0  0.609756
1  1985-86       Boston Celtics  67.0  15.0  0.817073
2  1985-86        Chicago Bulls  30.0  52.0  0.365854
3  1985-86  Cleveland Cavaliers  29.0  53.0  0.353659
4  1985-86     Dallas Mavericks  44.0  38.0  0.536585

In [31]:
# Select the team-season variables we initially want
team_features = all_team_seasons[
    [
        "Season",
        "Team",
        "W_PCT",
        "SRS",
        "ORtg",
        "DRtg",
        "NRtg",
        "Pace"
    ]
].copy()

# Create home-team version
home_features = team_features.rename(
    columns={
        "Team": "Home_Team",
        "W_PCT": "Home_W_PCT",
        "SRS": "Home_SRS",
        "ORtg": "Home_ORtg",
        "DRtg": "Home_DRtg",
        "NRtg": "Home_NRtg",
        "Pace": "Home_Pace"
    }
)

# Merge home-team regular-season stats onto each playoff game
model_data = all_playoff_games.merge(
    home_features,
    on=["Season", "Home_Team"],
    how="left"
)

print("Playoff games:", len(model_data))
print("\nMissing home-team matches:")
print(model_data["Home_SRS"].isna().sum())

Playoff games: 3143

Missing home-team matches:
0

In [32]:
# Create away-team version
away_features = team_features.rename(
    columns={
        "Team": "Away_Team",
        "W_PCT": "Away_W_PCT",
        "SRS": "Away_SRS",
        "ORtg": "Away_ORtg",
        "DRtg": "Away_DRtg",
        "NRtg": "Away_NRtg",
        "Pace": "Away_Pace"
    }
)

# Merge away-team regular-season stats onto each playoff game
model_data = model_data.merge(
    away_features,
    on=["Season", "Away_Team"],
    how="left"
)

print("Playoff games:", len(model_data))

print("\nMissing home-team matches:")
print(model_data["Home_SRS"].isna().sum())

print("\nMissing away-team matches:")
print(model_data["Away_SRS"].isna().sum())

Playoff games: 3143

Missing home-team matches:
0

Missing away-team matches:
0

In [33]:
# Create home-minus-away feature differences

model_data["W_PCT_Diff"] = (
    model_data["Home_W_PCT"] - model_data["Away_W_PCT"]
)

model_data["SRS_Diff"] = (
    model_data["Home_SRS"] - model_data["Away_SRS"]
)

model_data["ORtg_Diff"] = (
    model_data["Home_ORtg"] - model_data["Away_ORtg"]
)

model_data["DRtg_Diff"] = (
    model_data["Home_DRtg"] - model_data["Away_DRtg"]
)

model_data["NRtg_Diff"] = (
    model_data["Home_NRtg"] - model_data["Away_NRtg"]
)

model_data["Pace_Diff"] = (
    model_data["Home_Pace"] - model_data["Away_Pace"]
)

print(
    model_data[
        [
            "W_PCT_Diff",
            "SRS_Diff",
            "ORtg_Diff",
            "DRtg_Diff",
            "NRtg_Diff",
            "Pace_Diff",
            "Home_Win"
        ]
    ].isna().sum()
)

W_PCT_Diff    0
SRS_Diff      0
ORtg_Diff     0
DRtg_Diff     0
NRtg_Diff     0
Pace_Diff     0
Home_Win      0
dtype: int64

In [34]:
game7_2016 = model_data[
    (model_data["Season"] == "2015-16") &
    (model_data["Date"] == pd.Timestamp("2016-06-19")) &
    (model_data["Home_Team"] == "Golden State Warriors") &
    (model_data["Away_Team"] == "Cleveland Cavaliers")
]

game7_2016[
    [
        "Away_Team",
        "Away_W_PCT",
        "Away_SRS",
        "Away_ORtg",
        "Away_DRtg",
        "Away_NRtg",
        "Home_Team",
        "Home_W_PCT",
        "Home_SRS",
        "Home_ORtg",
        "Home_DRtg",
        "Home_NRtg",
        "W_PCT_Diff",
        "SRS_Diff",
        "NRtg_Diff",
        "Home_Win"
    ]
].T

                             2394
Away_Team     Cleveland Cavaliers
Away_W_PCT               0.695122
Away_SRS                     5.45
Away_ORtg                   110.9
Away_DRtg                   104.5
Away_NRtg                     6.4
Home_Team   Golden State Warriors
Home_W_PCT               0.890244
Home_SRS                    10.38
Home_ORtg                   114.5
Home_DRtg                   103.8
Home_NRtg                    10.7
W_PCT_Diff               0.195122
SRS_Diff                     4.93
NRtg_Diff                     4.3
Home_Win                        0

In [35]:
model_data.to_csv(
    "../data/nba_playoff_model_data_1986_2025.csv",
    index=False
)

print("Merged modeling dataset saved.")
print("Rows:", len(model_data))
print("Columns:", len(model_data.columns))

Merged modeling dataset saved.
Rows: 3143
Columns: 26

In [36]:
import os
print(os.getcwd())

/Users/jedcain/Documents/NBA_Championship_Luck_Project/notebooks